{{
    codegen.generate_source(
        database_name='alumno23_dev_bronze_db',
        schema_name='sql_server_dbo',
        generate_columns=true,
        include_descriptions=true,
        include_data_types=true,
        name='codegen_sql_server_dbo'
    )
}}